version: "3"
services:
  nginx:
    image: library/nginx:stable-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  node-app:
    build: .
    environment:
      - PORT=3000
    depends_on:
      - mongo

  mongo:
    image: webhippie/mongodb:latest
    volumes:
      - mongo-db:/data/db

  redis:
    image: redis


volumes:
  mongo-db: